/**
 * Central place for enums/constants shared across the backend.
 * Keeping these in one file avoids magic strings drifting apart
 * between models, controllers, and services.
 */

const ROLES = Object.freeze({
  USER: "USER",
  POLICE: "POLICE",
  GOVERNMENT_STAFF: "GOVERNMENT_STAFF",
  ADMIN: "ADMIN",
});

const RISK_LEVELS = Object.freeze({
  SAFE: "SAFE", // 0-30
  MODERATE: "MODERATE", // 31-60
  HIGH: "HIGH", // 61-80
  CRITICAL: "CRITICAL", // 81-100
});

const VIOLATION_TYPES = Object.freeze({
  OVERSPEEDING: "OVERSPEEDING",
  WRONG_SIDE_DRIVING: "WRONG_SIDE_DRIVING",
  RED_LIGHT_VIOLATION: "RED_LIGHT_VIOLATION",
  ILLEGAL_PARKING: "ILLEGAL_PARKING",
  DANGEROUS_DRIVING: "DANGEROUS_DRIVING",
  LANE_VIOLATION: "LANE_VIOLATION",
  HELMET_VIOLATION: "HELMET_VIOLATION",
  SEATBELT_VIOLATION: "SEATBELT_VIOLATION",
  MOBILE_PHONE_USAGE: "MOBILE_PHONE_USAGE",
  UNAUTHORIZED_ROAD_ENTRY: "UNAUTHORIZED_ROAD_ENTRY",
  REPEATED_UNSAFE_DRIVING: "REPEATED_UNSAFE_DRIVING",
});

const VIOLATION_REVIEW_STATUS = Object.freeze({
  PENDING_REVIEW: "PENDING_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  MORE_REVIEW_REQUIRED: "MORE_REVIEW_REQUIRED",
});

const FINE_STATUS = Object.freeze({
  PENDING: "PENDING",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
  DISPUTED: "DISPUTED",
  UNDER_REVIEW: "UNDER_REVIEW",
  CANCELLED: "CANCELLED",
});

const PAYMENT_STATUS = Object.freeze({
  INITIATED: "INITIATED",
  PROCESSING: "PROCESSING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  PENDING: "PENDING",
});

const PAYMENT_METHODS = Object.freeze({
  UPI: "UPI",
  GOOGLE_PAY: "GOOGLE_PAY",
  PHONEPE: "PHONEPE",
  FASTAG: "FASTAG",
  OTHER: "OTHER",
});

const DISPUTE_STATUS = Object.freeze({
  RECEIVED: "RECEIVED",
  UNDER_REVIEW: "UNDER_REVIEW",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  MORE_INFO_REQUESTED: "MORE_INFO_REQUESTED",
});

const NOTIFICATION_CHANNELS = Object.freeze({
  IN_APP: "IN_APP",
  SMS: "SMS",
  WHATSAPP: "WHATSAPP",
  EMAIL: "EMAIL",
});

const NOTIFICATION_STATUS = Object.freeze({
  QUEUED: "QUEUED",
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  FAILED: "FAILED",
});

const REMINDER_LEVELS = Object.freeze({
  FIRST: "FIRST_IN_APP",
  SECOND: "SECOND_SMS",
  THIRD: "THIRD_WHATSAPP",
  FINAL: "FINAL_OVERDUE",
});

const HAZARD_TYPES = Object.freeze({
  POTHOLE: "POTHOLE",
  ACCIDENT: "ACCIDENT",
  ROAD_DAMAGE: "ROAD_DAMAGE",
  FLOODING: "FLOODING",
  CONSTRUCTION: "CONSTRUCTION",
  OBSTACLE: "OBSTACLE",
  DANGEROUS_CURVE: "DANGEROUS_CURVE",
  POOR_VISIBILITY: "POOR_VISIBILITY",
});

const HAZARD_SEVERITY = Object.freeze({
  LOW: "LOW",
  MODERATE: "MODERATE",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
});

const NEAR_MISS_TYPES = Object.freeze({
  SUDDEN_BRAKING: "SUDDEN_BRAKING",
  NEAR_COLLISION: "NEAR_COLLISION",
  UNSAFE_OVERTAKING: "UNSAFE_OVERTAKING",
  PEDESTRIAN_RISK: "PEDESTRIAN_RISK",
  LANE_DEPARTURE: "LANE_DEPARTURE",
  WRONG_SIDE_AVOIDANCE: "WRONG_SIDE_AVOIDANCE",
});

const DETECTION_SOURCE = Object.freeze({
  AI_CAMERA: "AI_CAMERA",
  AI_LIVE_DRIVE: "AI_LIVE_DRIVE_SESSION",
  USER_REPORT: "USER_REPORT",
  OFFICER_MANUAL: "OFFICER_MANUAL_ENTRY",
});

const AUDIT_ACTIONS = Object.freeze({
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  USER_SEARCH: "USER_SEARCH",
  VIOLATION_VIEWED: "VIOLATION_VIEWED",
  VIOLATION_APPROVED: "VIOLATION_APPROVED",
  VIOLATION_REJECTED: "VIOLATION_REJECTED",
  FINE_CREATED: "FINE_CREATED",
  FINE_UPDATED: "FINE_UPDATED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  NOTIFICATION_SENT: "NOTIFICATION_SENT",
  DISPUTE_DECISION: "DISPUTE_DECISION",
  RECEIPT_ACCESSED: "RECEIPT_ACCESSED",
});

const EMERGENCY_STATUS = Object.freeze({
  DETECTED: "DETECTED",
  AWAITING_RESPONSE: "AWAITING_RESPONSE",
  CONFIRMED_FALSE_ALARM: "CONFIRMED_FALSE_ALARM",
  EMERGENCY_EVENT_CREATED: "EMERGENCY_EVENT_CREATED",
  RESOLVED: "RESOLVED",
});

module.exports = {
  ROLES,
  RISK_LEVELS,
  VIOLATION_TYPES,
  VIOLATION_REVIEW_STATUS,
  FINE_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHODS,
  DISPUTE_STATUS,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUS,
  REMINDER_LEVELS,
  HAZARD_TYPES,
  HAZARD_SEVERITY,
  NEAR_MISS_TYPES,
  DETECTION_SOURCE,
  AUDIT_ACTIONS,
  EMERGENCY_STATUS,
};
